REDIS_HOST=judge0-redis
REDIS_PORT=6379

POSTGRES_HOST=judge0-postgres
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0secret

WORKERS_MAX_PROCESSES=4
ENABLE_WAIT_RESULT=true
ALLOW_ENABLE_WAIT_RESULT=true

CPU_TIME_LIMIT=5
CPU_EXTRA_TIME=1
WALL_TIME_LIMIT=10
MEMORY_LIMIT=128000
MAX_FILE_SIZE=1024
MAX_NUMBER_OF_PROCESSES=60

ENABLE_ADDITIONAL_FILES=false